import type { Metadata } from "next";
import "@/styles/globals.css";
import { Poppins } from 'next/font/google';
import Providers from "./Providers";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Shopnest",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: [
    '100', '200', '300', '400', '500', '600', '700', '800', '900',
  ],
  style: ['normal', 'italic'],
  variable: '--font-poppins',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={poppins.className}>
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
